// authentication related actiontypes
export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const LOGOUT = 'LOGOUT';

// Forget/Reset password related actiontypes
export const PASSWORD_RESET_INST_INIT = 'PASSWORD_RESET_INST_INIT';
export const PASSWORD_RESET_INST_SUCCESS = 'PASSWORD_RESET_INST_SUCCESS';
export const PASSWORD_RESET_INST_FAIL = 'PASSWORD_RESET_INST_FAIL';
export const PASSWORD_RESET_INIT = 'PASSWORD_RESET_INIT';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const PASSWORD_CHANGE_INIT = 'PASSWORD_CHANGE_INIT';
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS';
export const PASSWORD_CHANGE_FAIL = 'PASSWORD_CHANGE_FAIL';

// dashboard related actionTypes
export const FETCH_DASHBOARD_STATISTICS_INIT = 'FETCH_DASHBOARD_STATISTICS_INIT';
export const FETCH_DASHBOARD_STATISTICS_SUCCESS = 'FETCH_DASHBOARD_STATISTICS_SUCCESS';
export const FETCH_DASHBOARD_STATISTICS_FAIL = 'FETCH_DASHBOARD_STATISTICS_FAIL';

// excercise related actionTypes
export const FETCH_COMPLETION_SCREEN_DROPDOWN_LIST_INIT = 'FETCH_COMPLETION_SCREEN_DROPDOWN_LIST_INIT';
export const FETCH_COMPLETION_SCREEN_DROPDOWN_LIST_SUCCESS = 'FETCH_COMPLETION_SCREEN_DROPDOWN_LIST_SUCCESS';
export const FETCH_COMPLETION_SCREEN_DROPDOWN_LIST_FAIL = 'FETCH_COMPLETION_SCREEN_DROPDOWN_LIST_FAIL';

export const FETCH_EXCERCISE_LIST_INIT = 'FETCH_EXCERCISE_LIST_INIT';
export const FETCH_EXCERCISE_LIST_SUCCESS = 'FETCH_EXCERCISE_LIST_SUCCESS';
export const FETCH_EXCERCISE_LIST_FAIL = 'FETCH_EXCERCISE_LIST_FAIL';

export const FETCH_EXCERCISE_DETAIL_INIT = 'FETCH_EXCERCISE_DETAIL_INIT';
export const FETCH_EXCERCISE_DETAIL_SUCCESS = 'FETCH_EXCERCISE_DETAIL_SUCCESS';
export const FETCH_EXCERCISE_DETAIL_FAIL = 'FETCH_EXCERCISE_DETAIL_FAIL';

export const SORT_EXERCISE_INIT = 'SORT_EXERCISE_INIT';
export const SORT_EXERCISE_SUCCESS = 'SORT_EXERCISE_SUCCESS';
export const SORT_EXERCISE_FAIL = 'SORT_EXERCISE_FAIL';

export const ADD_EXCERCISE_INIT = 'ADD_EXCERCISE_INIT';
export const ADD_EXCERCISE_SUCCESS = 'ADD_EXCERCISE_SUCCESS';
export const ADD_EXCERCISE_FAIL = 'ADD_EXCERCISE_FAIL';

export const UPDATE_EXERCISE_INIT = 'UPDATE_EXERCISE_INIT';
export const UPDATE_EXERCISE_SUCCESS = 'UPDATE_EXERCISE_SUCCESS';
export const UPDATE_EXERCISE_FAIL = 'UPDATE_EXERCISE_FAIL';

export const DELETE_EXCERCISE_INIT = 'DELETE_EXCERCISE_INIT';
export const DELETE_EXCERCISE_SUCCESS = 'DELETE_EXCERCISE_SUCCESS';
export const DELETE_EXCERCISE_FAIL = 'DELETE_EXCERCISE_FAIL';

export const UPDATE_EXCERCISEINFO_INIT = 'UPDATE_EXCERCISEINFO_INIT';
export const UPDATE_EXCERCISEINFO_SUCCESS = 'UPDATE_EXCERCISEINFO_SUCCESS';
export const UPDATE_EXCERCISEINFO_FAIL = 'UPDATE_EXCERCISEINFO_FAIL';

export const NO_ACTION = 'NO_ACTION';
export const RESET_MODAL_STATUS = 'RESET_MODAL_STATUS';
export const RESET_MESSAGE = 'RESET_MESSAGE';
export const CHANGE_TAB = 'CHANGE_TAB';

// graph modal related actions

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SIDENAV_CLICK = 'SIDENAV_CLICK';
export const ADD_SUCCESS_NOTIFICATION = 'ADD_SUCCESS_NOTIFICATION';
export const ADD_ERROR_NOTIFICATION = 'ADD_ERROR_NOTIFICATION';